pipeline {
  agent any
  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }
    stage('Test') {
      agent {
        docker {
          image 'python:3.6-slim'
        }
      }
      steps {
        echo 'Instalando dependencias del sistema...'
        sh 'apt-get update && apt-get install -y make'
        
        echo 'Instalando dependencias de Python...'
        sh 'pip install -r requirements.txt pytest'
        
        echo 'Ejecutando tests unitarios...'
        sh 'pytest tests/'
      }
    }
  }
}