// EJERCICIO 4: Función Groovy reutilizable
def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()
    }
}

// EJERCICIO 10: "Mini librería" para Compose
def composeUpTestDown(Map args) {
    try {
        echo "--> [composeUpTestDown] Ejecutando UP..."
        sh args.up
        
        echo "--> [composeUpTestDown] Ejecutando TEST/VALIDACION..."
        sh args.test
    } finally {
        // El bloque finally asegura que esto se ejecuta SIEMPRE, aunque el test falle
        echo "--> [composeUpTestDown] Ejecutando DOWN (Limpieza)..."
        sh "${args.down} || true"
    }
}

pipeline {
  agent any

  // EJERCICIO 6.3: Parámetros para activar/desactivar comportamiento
  parameters {
    booleanParam(name: 'RUN_CD', defaultValue: false, description: 'Ejecutar CD')
    // EJERCICIO 7: Parámetro para activar la subida al registry
    booleanParam(name: 'ENABLE_REGISTRY_PUSH', defaultValue: false, description: 'Subir imagen al registry privado')
  }

  // EJERCICIO 6.4: Variables de entorno
  environment {
    CI_IMAGE_NAME = "python-ci-tools:${env.BUILD_NUMBER}"
    IMAGE_NAME = "contrerasadr/devops-training-python-app:0.0.1"
    APP_URL = "http://localhost:5001/"
    // EJERCICIO 7: Variable con la ruta del registry local
    REGISTRY_IMAGE = "local-registry:5000/contrerasadr/devops-training-python-app:${env.BUILD_NUMBER}"
  }
  
  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }

    // EJERCICIO 3: Construir imagen CI con make
    stage('CI - Build tools image') {
      steps {
        script {
          echo 'Construyendo la imagen Docker de herramientas CI...'
          docker.build("python-ci-tools:${env.BUILD_NUMBER}", "-f devops/ci.Dockerfile .")
        }
      }
    }

    // EJERCICIO 3 y 4: Separar stage Lint y usar función Groovy
    stage('CI - Lint') {
      steps {
        script {
          // Usar la nueva función en lugar de docker.image().inside
          runInDocker(env.CI_IMAGE_NAME) { // Utilizar la variable de entorno
            echo 'Instalando dependencias de Lint...'
            sh 'pip install -r requirements.txt flake8 mypy'
            
            echo 'Ejecutando revisión de código...'
            sh 'make lint'
          }
        }
      }
    }

    // EJERCICIO 3 y 4: Separar stage Test y usar función Groovy
    stage('CI - Test') {
      steps {
        script {
          // Usar la nueva función en lugar de docker.image().inside
          runInDocker(env.CI_IMAGE_NAME) { // Utilizar la variable de entorno
            echo 'Instalando dependencias para las pruebas...'
            sh 'pip install -r requirements.txt pytest flake8 mypy'
            
            echo 'Ejecutando tests unitarios...'
            sh 'make test'
          }
        }
      }
    }
    
    // EJERCICIO 5: Construir la imagen Docker en CI
    stage('Build image') {
      steps {
        script {
          // Uso de la variable de entorno del Ejercicio 6.4
          echo "Imagen: ${env.IMAGE_NAME}"
          docker.build("${env.IMAGE_NAME}", "-f devops/Dockerfile .") // Se contruye usando el Dockerfile principal de la aplicación
        }
      }
    }

    // EJERCICIO 7: Push a un registry privado
    stage('Push image') {
      when {
        expression { return params.ENABLE_REGISTRY_PUSH }
      }
      steps {
        script {
          echo "Etiquetando la imagen para el registry local..."
          sh "docker tag ${env.IMAGE_NAME} ${env.REGISTRY_IMAGE}"
          
          echo "Autenticando y subiendo al registry..."
          // Usamos las credenciales de Jenkins
          withCredentials([usernamePassword(credentialsId: 'local-registry-creds', passwordVariable: 'REG_PASS', usernameVariable: 'REG_USER')]) {
            sh "docker login -u ${REG_USER} -p ${REG_PASS} local-registry:5000"
            sh "docker push ${env.REGISTRY_IMAGE}"
          }
        }
      }
    }

    // EJERCICIO 6: CD con Docker Compose (up -> logs -> down)
    // EJERCICIOS 6.1 al 6.5 aplicados en el CD
    stage('CD') {
      // EJERCICIO 6.1: Ejecutar CD por rama o parámetro
      when {
        anyOf {
          expression { return params.RUN_CD }
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        script {
          // EJERCICIO 6.2: Simular despliegue a DEV/PRO
          env.DEPLOY_ENV = (env.BRANCH_NAME == 'master') ? 'pro' : 'dev'
          echo "Deploying to ${env.DEPLOY_ENV}"

          // EJERCICIO 10: Uso de la función pasándole un mapa (Map args)
          composeUpTestDown(
            up: "docker compose -p ${env.DEPLOY_ENV} up -d && sleep 5",
            test: "echo URL=${env.APP_URL} && docker compose -p ${env.DEPLOY_ENV} logs app",
            down: "docker compose -p ${env.DEPLOY_ENV} down --volumes"
          )
        }
      }
      // EJERCICIO 6.5: Hooks post y limpieza de recursos
      post {
        always {
          // La limpieza del compose down ya la hace la función. Aquí sólo se borra la imagen local.
          sh "docker rmi ${env.IMAGE_NAME} || true"
        }
        success {
          echo 'SUCCESS'
        }
        failure {
          echo 'FAILURE'
        }
      }
    }
  }
}