// EJERCICIO 4: Función Groovy reutilizable
def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()
    }
}

pipeline {
  agent any
  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }

    // EJERCICIO 3: Construir imagen CI con make
    stage('CI - Build tools image') {
      steps {
        script {
          echo 'Construyendo la imagen Docker de herramientas CI...'
          docker.build("python-ci-tools:${env.BUILD_NUMBER}", "-f devops/ci.Dockerfile .")
        }
      }
    }

    // EJERCICIO 3 y 4: Separar stage Lint y usar función Groovy
    stage('CI - Lint') {
      steps {
        script {
          // Usar la nueva función en lugar de docker.image().inside
          runInDocker("python-ci-tools:${env.BUILD_NUMBER}") {
            echo 'Instalando dependencias de Lint...'
            sh 'pip install -r requirements.txt flake8 mypy'
            
            echo 'Ejecutando revisión de código...'
            sh 'make lint'
          }
        }
      }
    }

    // EJERCICIO 3 y 4: Separar stage Test y usar función Groovy
    stage('CI - Test') {
      steps {
        script {
          // Usar la nueva función en lugar de docker.image().inside
          runInDocker("python-ci-tools:${env.BUILD_NUMBER}") {
            echo 'Instalando dependencias para las pruebas...'
            sh 'pip install -r requirements.txt pytest flake8 mypy'
            
            echo 'Ejecutando tests unitarios...'
            sh 'make test'
          }
        }
      }
    }
    
    // EJERCICIO 5: Construir la imagen Docker en CI
    stage('Build image') {
      steps {
        script {
          echo 'Construyendo la imagen Docker de la aplicación...'
          docker.build("contrerasadr/devops-training-python-app:0.0.1", "-f devops/Dockerfile .") // Se contruye usando el Dockerfile principal de la aplicación
        }
      }
    }

    // EJERCICIO 6: CD con Docker Compose (up -> logs -> down)
    stage('CD') {
      steps {
        echo 'Iniciando despliegue local con Docker Compose...'
        sh 'docker compose up -d'
        
        echo 'Esperando 5 segundos a que levante el servicio...'
        sh 'sleep 5'
        
        echo 'Mostrando logs del contenedor principal para validar el despliegue...'
        sh 'docker compose logs app' // 'app' es el nombre del servicio en el docker-compose.yml
      }
      post {
        always {
          echo 'Ejecutando limpieza de recursos temporales...'
          sh 'docker compose down --volumes' // Esto se ejecuta SIEMPRE, incluso si fallan los steps anteriores
        }
      }
    }
  }
}